### ISSUE TITLE
a suggestion 

### ISSUE THREAD

**Issue by takeoff9** [dxnter/lasty#10]
can you add a whoknows command? for tracks, albums and artists please...

**Comment by dxnter** [comment]
Yeah, it's on my todo list. I've been busy so I haven't pushed many updates but it is planned.

**Comment by renotify** [comment]
dope. I can't wait!

**Comment by dxnter** [comment]
@takeoff9 Added all those commands in the latest release. https://github.com/dxnter/lasty/releases/tag/2.4.0
