### ISSUE TITLE
hosting: heroku

### ISSUE THREAD

**Issue by HavinFiles** [dxnter/lasty#14]
Is this even possible with the typescript???

I tried, and this is the error I get every time:

`npm ERR! Error while executing:
       npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/discordjs/Commando.git
       npm ERR! 
       npm ERR! Host key verification failed.
       npm ERR! fatal: Could not read from remote repository.
       npm ERR! 
       npm ERR! Please make sure you have the correct access rights
       npm ERR! and the repository exists.
       npm ERR! 
       npm ERR! exited with error code: 128
       npm ERR! A complete log of this run can be found in: `

Not really sure what this means, but I added nodejs and typescript buildpacks to it on Heroku and it won’t work. Let me know, Thanks!

**Comment by dxnter** [comment]
It should be possible on TypeScript, this looks like an issue with installing a package.

In `package.json`, change line 38 to:
```json
"discord.js-commando": "^0.10.0"
```
Let me know if that fixes the error, I'll push the fix in the next version. Sorry for the late reply, don't hesitate to add me on Discord, `dxnter#0001`, for a quicker response.
