### ISSUE TITLE
new bug? track not found!

### ISSUE THREAD

**Issue by NexifyUS** [dxnter/lasty#4]
alot of my discord users are experiencing issues using the bot with spotify since some tracks when running the np command will output "Track not found!"

**Comment by NexifyUS** [comment]
guessing this project and dev is long gone so ima just redownload and find out whats wrong or try a new bot

**Comment by dxnter** [comment]
Apologies, I didn't have GitHub notifications enabled so I just saw this now. 

Could you provide tracks in which this happens? From my experience, there would be tracks I listened to that weren't submitted to Last.FM and I added this error message as a workaround.

**Comment by HavinFiles** [comment]
this error Happens with each and every one of Pi'erre Bourne's songs.

**Comment by dxnter** [comment]
![image](https://user-images.githubusercontent.com/17434202/97524903-a7147000-1973-11eb-8a49-4d37619f88eb.png)

@HavinFiles Seems to be working fine for me. Are you on the most recent version?

**Comment by dxnter** [comment]
![](https://i.imgur.com/2V23O79.png)

@HavinFiles Seems to be working fine for me in `np` and `recent`. Are you on the most recent version?

**Comment by HavinFiles** [comment]
That might be the problem, It was an earlier version. Try one pierre song from the album "The Life Of Pierre 4", those were the ones not working for me

If it's fixed, my apologies for even bringing it up lmaoo

**Comment by dxnter** [comment]
Works for the original TLOP4 too. No worries about bringing it up, it definitely didn't work in earlier versions. It had to do with the apostrophe in his name messing the command up. That bug is fixed now but please open a new issue if you do come across problems with another artist.
