### ISSUE TITLE
Bot responds to literally any character as prefix.

### ISSUE THREAD

**Issue by cood1n** [dxnter/lasty#6]

**Comment by gain-on-jah** [comment]
Add
`if (!message.content.startsWith(PREFIX)) return;`
to bot.js under
`if (message.channel.type === 'dm') return;`

**Comment by dxnter** [comment]
I'm surprised I've been using this for so long without ever realizing the prefix didn't matter. Updated in a9fa4c068615f7eefc67c1ebf5afabe56a4ecb03.

Thanks for the fix @gain-on-jah.
